name: GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        run: echo "Stats ready"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
